"""Runtime event types emitted by ASCOS domain operations."""

from enum import Enum

from runtime.exceptions import InvalidEventTypeError


class EventType(str, Enum):
    WORK_PACKAGE_CREATED = "WORK_PACKAGE_CREATED"
    WORK_ITEM_CREATED = "WORK_ITEM_CREATED"
    WORK_ITEM_STATE_CHANGED = "WORK_ITEM_STATE_CHANGED"
    AGENT_REGISTERED = "AGENT_REGISTERED"
    AGENT_STATE_CHANGED = "AGENT_STATE_CHANGED"
    ASSIGNMENT_CREATED = "ASSIGNMENT_CREATED"
    ASSIGNMENT_COMPLETED = "ASSIGNMENT_COMPLETED"
    ASSIGNMENT_CANCELLED = "ASSIGNMENT_CANCELLED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    EXECUTION_SUCCEEDED = "EXECUTION_SUCCEEDED"
    EXECUTION_FAILED = "EXECUTION_FAILED"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    EXECUTION_RECOVERY_RETRIED = "EXECUTION_RECOVERY_RETRIED"
    EXECUTION_RECOVERY_RESET = "EXECUTION_RECOVERY_RESET"
    EXECUTION_RECOVERY_CANCELLED = "EXECUTION_RECOVERY_CANCELLED"
    SOFTWARE_REQUEST_SUBMITTED = "SOFTWARE_REQUEST_SUBMITTED"
    SOFTWARE_REQUEST_PLANNED = "SOFTWARE_REQUEST_PLANNED"
    SOFTWARE_WORK_ASSIGNED = "SOFTWARE_WORK_ASSIGNED"
    SOFTWARE_EXECUTION_STARTED = "SOFTWARE_EXECUTION_STARTED"
    SOFTWARE_EXECUTION_SUCCEEDED = "SOFTWARE_EXECUTION_SUCCEEDED"
    SOFTWARE_EXECUTION_FAILED = "SOFTWARE_EXECUTION_FAILED"
    SOFTWARE_REVIEW_SUBMITTED = "SOFTWARE_REVIEW_SUBMITTED"
    SOFTWARE_WORK_APPROVED = "SOFTWARE_WORK_APPROVED"
    SOFTWARE_WORK_REJECTED = "SOFTWARE_WORK_REJECTED"
    SOFTWARE_WORK_COMPLETED = "SOFTWARE_WORK_COMPLETED"
    SOFTWARE_WORK_RELEASED = "SOFTWARE_WORK_RELEASED"
    SOFTWARE_WORKFLOW_CANCELLED = "SOFTWARE_WORKFLOW_CANCELLED"
    SOFTWARE_EXECUTION_RECOVERED = "SOFTWARE_EXECUTION_RECOVERED"


def validate_event_type(value: object) -> None:
    if not isinstance(value, EventType):
        raise InvalidEventTypeError(
            "event_type must be an EventType enum value"
        )
