from typing import Protocol


class ProviderHealthRepository(Protocol):
    def add(self, state): ...
    def get(self, provider_id, capability): ...
    def list(self): ...
    def save(self, state, *, expected_version): ...
