"""Runtime foundation package for ASCOS."""

from runtime.exceptions import (
    AgentCapacityError,
    AgentNotFoundError,
    AssignmentNotFoundError,
    ArtifactNotFoundError,
    DuplicateAgentError,
    DuplicateActiveAssignmentError,
    DuplicateArtifactError,
    DuplicateExecutionError,
    DuplicateExecutorError,
    DuplicateWorkItemError,
    DuplicateWorkPackageError,
    ExecutionFailedError,
    ExecutionNotFoundError,
    ExecutorNotFoundError,
    InvalidAgentStateTransitionError,
    InvalidAssignmentStateTransitionError,
    InvalidExecutionStateTransitionError,
    InvalidLifecycleTransitionError,
    NoEligibleAgentError,
    RuntimeDomainError,
    ValidationError,
    WorkItemNotFoundError,
    WorkPackageNotFoundError,
)

__all__ = [
    "AgentCapacityError",
    "AgentNotFoundError",
    "AssignmentNotFoundError",
    "ArtifactNotFoundError",
    "DuplicateAgentError",
    "DuplicateActiveAssignmentError",
    "DuplicateArtifactError",
    "DuplicateExecutionError",
    "DuplicateExecutorError",
    "DuplicateWorkItemError",
    "DuplicateWorkPackageError",
    "ExecutionFailedError",
    "ExecutionNotFoundError",
    "ExecutorNotFoundError",
    "InvalidAgentStateTransitionError",
    "InvalidAssignmentStateTransitionError",
    "InvalidExecutionStateTransitionError",
    "InvalidLifecycleTransitionError",
    "NoEligibleAgentError",
    "RuntimeDomainError",
    "ValidationError",
    "WorkItemNotFoundError",
    "WorkPackageNotFoundError",
]
