from typing import Protocol


class CodingAgentProvider(Protocol):
    provider_id: str
    priority: int
    def supported_capabilities(self): ...
    def is_available(self): ...
    def submit_task(self, request): ...
    def get_task_status(self, provider_task_id): ...
    def get_progress(self, provider_task_id): ...
    def get_result(self, provider_task_id): ...
    def cancel_task(self, provider_task_id): ...
