from typing import Protocol


class GitProvider(Protocol):
    def initialize(self, repository_path): ...
    def status(self, repository_path): ...
    def create_branch(self, repository_path, branch: str): ...
    def commit(self, repository_path, message: str): ...
