from typing import Protocol


class GitHubProvider(Protocol):
    def get_repository(self, reference): ...
    def get_branch(self, repository, branch): ...
    def create_draft_pull_request(self, request): ...
    def mark_ready_for_review(self, repository, number): ...
    def merge_pull_request(self, repository, number, *, approved: bool): ...
