from typing import Protocol


class OutboxRepository(Protocol):
    def add_operation(self, operation): ...
    def get_operation(self, operation_id): ...
    def claim_next(self, owner_id, *, ttl_seconds=30): ...
    def mark_dispatching(self, claim): ...
    def mark_succeeded(self, claim, result_reference): ...
