"""Typed provider contract. Providers cannot approve or mutate Git/GitHub."""

from typing import Protocol


class CodingProvider(Protocol):
    provider_id: str

    def validate_configuration(self) -> None: ...
    def capabilities(self): ...
    def submit_task(self, request): ...
    def get_task_status(self, provider_task_id): ...
    def get_task_progress(self, provider_task_id): ...
    def get_task_result(self, provider_task_id): ...
    def cancel_task(self, provider_task_id): ...
    def reconcile_task(self, idempotency_key, provider_task_id=None): ...
