"""Bounded Software Architect agent for ASCOS Day 24."""

from runtime.workforce_architecture.errors import (
    ArchitectureWorkforceConflict,
    ArchitectureWorkforceCorrupt,
    ArchitectureWorkforceError,
    ArchitectureWorkforceNotFound,
    ArchitectureWorkforcePolicyError,
)
from runtime.workforce_architecture.models import (
    ADR_STATUS,
    ARCHITECT_ACTION_IDS,
    ARCHITECT_CAPABILITY_IDS,
    ARTIFACT_STATUS,
    DRAFT_ARCHITECTURE_DECISIONS,
    IDENTIFY_TECHNICAL_RISKS,
    PILOT_STATUS,
    PROPOSE_SOFTWARE_ARCHITECTURE,
    RECOMMEND_TECHNOLOGY,
    RECOMMENDATION_STATUS,
    REPORT_ARCHITECTURE_STATUS,
    WORK_STATUS,
    ArchitectureComponent,
    ArchitectureDecisionDraft,
    ArchitectureProposalArtifact,
    ArchitectureStatusReport,
    RiskLikelihood,
    RiskSeverity,
    TechnicalRisk,
    TechnologyRecommendation,
    artifact_id_for,
)
from runtime.workforce_architecture.persistence import FileArchitectureArtifactStore
from runtime.workforce_architecture.provider import SoftwareArchitectProvider
from runtime.workforce_architecture.service import (
    ArchitectureWorkforceService,
    architecture_objective,
)

__all__ = [
    "ADR_STATUS",
    "ARCHITECT_ACTION_IDS",
    "ARCHITECT_CAPABILITY_IDS",
    "ARTIFACT_STATUS",
    "ArchitectureComponent",
    "ArchitectureDecisionDraft",
    "ArchitectureProposalArtifact",
    "ArchitectureStatusReport",
    "ArchitectureWorkforceConflict",
    "ArchitectureWorkforceCorrupt",
    "ArchitectureWorkforceError",
    "ArchitectureWorkforceNotFound",
    "ArchitectureWorkforcePolicyError",
    "ArchitectureWorkforceService",
    "DRAFT_ARCHITECTURE_DECISIONS",
    "FileArchitectureArtifactStore",
    "IDENTIFY_TECHNICAL_RISKS",
    "PILOT_STATUS",
    "PROPOSE_SOFTWARE_ARCHITECTURE",
    "RECOMMEND_TECHNOLOGY",
    "RECOMMENDATION_STATUS",
    "REPORT_ARCHITECTURE_STATUS",
    "RiskLikelihood",
    "RiskSeverity",
    "SoftwareArchitectProvider",
    "TechnicalRisk",
    "TechnologyRecommendation",
    "WORK_STATUS",
    "architecture_objective",
    "artifact_id_for",
]
